name: MSBuild

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  PFX_FILE_NAME: OutlookCloseToMinimize_TemporaryKey.pfx

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path ${{env.SOLUTION_FILE_PATH}} -ChildPath ${{env.PFX_FILE_NAME}}
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path ${{env.SOLUTION_FILE_PATH}}/${{env.PFX_FILE_NAME}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{env.SOLUTION_FILE_PATH}}/bin/${{env.BUILD_CONFIGURATION}}/**
